### ISSUE TITLE
ActiveRecord::ConnectionNotEstablished: No connection pool with id primary found

### ISSUE THREAD

**Issue by vladra** [influitive/apartment-sidekiq#13]
Having this error `ActiveRecord::ConnectionNotEstablished: No connection pool with id primary found` using sidekiq with 5 threads and db pool size set to 10.

Anyone got same? Any tips to solve this?

Rails 5. Stack trace:
```
ActiveRecord::ConnectionNotEstablished: No connection pool with id primary found.
  from active_record/connection_adapters/abstract/connection_pool.rb:876:in `retrieve_connection'
  from active_record/connection_handling.rb:128:in `retrieve_connection'
  from active_record/connection_handling.rb:91:in `connection'
  from apartment/adapters/abstract_adapter.rb:53:in `current'
  from apartment/adapters/abstract_adapter.rb:96:in `switch'
  from apartment/sidekiq/middleware/server.rb:4:in `call'
  from sidekiq/middleware/chain.rb:130:in `block in invoke'
  from sidekiq/middleware/server/logging.rb:11:in `block in call'
  from sidekiq/logging.rb:32:in `with_context'
  from sidekiq/middleware/server/logging.rb:7:in `call'
  from sidekiq/middleware/chain.rb:130:in `block in invoke'
  from sidekiq/middleware/chain.rb:133:in `invoke'
  from sidekiq/processor.rb:129:in `block in process'
  from sidekiq/processor.rb:168:in `stats'
  from sidekiq/processor.rb:128:in `process'
  from sidekiq/processor.rb:80:in `process_one'
  from sidekiq/processor.rb:68:in `run'
  from sidekiq/util.rb:17:in `watchdog'
  from sidekiq/util.rb:25:in `block in safe_thread'
```

**Comment by vladra** [comment]
Actually this is related to my issue in apartment repo, should think better before posting. Pretty sure it's not thread safe problem from apartment gem.

https://github.com/influitive/apartment/issues/311

**Comment by saravyas** [comment]
I too getting this error could you solve it

**Comment by yangbo1987** [comment]
how could you resolve it ,i got it same
